// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR71n2pc7c9FL_y1CMMmS1vlX_DO8UiuI',
    appId: '1:1038718448666:web:0dfec7d30281e0bf764da3',
    messagingSenderId: '1038718448666',
    projectId: 'flutter-92ded',
    authDomain: 'flutter-92ded.firebaseapp.com',
    storageBucket: 'flutter-92ded.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRqoGh38jUaomf6dwE7w9cPmfS2b7qwmI',
    appId: '1:1038718448666:android:7486da0a4d7f099a764da3',
    messagingSenderId: '1038718448666',
    projectId: 'flutter-92ded',
    storageBucket: 'flutter-92ded.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACPMa2w9wP3s3iPLXLqvloJLBHovHdpVU',
    appId: '1:1038718448666:ios:728cb922b0630149764da3',
    messagingSenderId: '1038718448666',
    projectId: 'flutter-92ded',
    storageBucket: 'flutter-92ded.appspot.com',
    iosClientId: '1038718448666-pmtb53go26drukvvuq7nfj1mi7of6a6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACPMa2w9wP3s3iPLXLqvloJLBHovHdpVU',
    appId: '1:1038718448666:ios:728cb922b0630149764da3',
    messagingSenderId: '1038718448666',
    projectId: 'flutter-92ded',
    storageBucket: 'flutter-92ded.appspot.com',
    iosClientId: '1038718448666-pmtb53go26drukvvuq7nfj1mi7of6a6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireBase',
  );
}
